services:
  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: hospital_php
    volumes:
      - ./app:/var/www/html
      - ./static-files:/var/www/html/static
    environment:
      - DB_HOST=193.219.91.104
      - DB_PORT=3545
      - DB_NAME=hospital
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always

  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: hospital_nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./app:/var/www/html
      - ./static-files:/var/www/html/static
    restart: always
