services:
  app:
    build:
      context: .
      dockerfile: Web/php.Dockerfile
    container_name: hospital_php
    volumes:
      - ./Web:/var/www/html
    environment:
      - DB_HOST=193.219.91.103
      - DB_PORT=9206
      - DB_NAME=hospital
      - DB_USER=hospital_owner
      - DB_PASSWORD=iLoveUnix
    restart: always

  web:
    build:
      context: .
      dockerfile: Web/nginx.Dockerfile
    container_name: hospital_nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./Web:/var/www/html
    restart: always
