services:
  app:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: hospital_php
    volumes:
      - ./app:/var/www/html
      - ./static-files:/var/www/html/static
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5433
      - DB_NAME=hospital
      - DB_USER=postgres
      - DB_PASSWORD=159511
    restart: always

  web:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: hospital_nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./app:/var/www/html
      - ./static-files:/var/www/html/static
    restart: always
