services:
  app:
    build:
      context: .
      dockerfile: Web/php.Dockerfile
    container_name: hospital_php
    volumes:
      - ./Web:/var/www/html
    environment:
      - DB_HOST=${DB_IP}
      - DB_PORT=5432
      - DB_NAME=hospital
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: always

  web:
    build:
      context: .
      dockerfile: Web/nginx.Dockerfile
    container_name: hospital_nginx
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./Web:/var/www/html
    restart: always
